### ISSUE TITLE
ModuleNotFoundError from mkl_fft-1.0.4

### ISSUE THREAD

**Issue by awst-baum** [TUW-GEO/pytesmo#145]
When testing pytesmo in a freshly created conda env, I get issues with mkl_fft-1.0.4 throwing ModuleNotFoundError during the tests.

The env is created with:

    conda create --yes -n deptest -c conda-forge python=2.7 numpy scipy pandas=0.22 netCDF4 cython pytest pip matplotlib pyproj

and that automatically installs mkl_fft-1.0.4 on the machines I'm testing on.

The unit tests then fail with:

    Traceback (most recent call last):
    File "setup.py", line 66, in <module>
        setup_package()
    File "setup.py", line 62, in setup_package
        use_pyscaffold=True)
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/code/.eggs/PyScaffold-2.5.11-py2.7.egg/pyscaffold/pytest_runner.py", line 101, in run
        self.with_project_on_sys_path(self.run_tests)
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/site-packages/setuptools/command/test.py", line 126, in with_project_on_sys_path
        with self.project_on_sys_path():
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/site-packages/setuptools/command/test.py", line 154, in project_on_sys_path
        self.run_command('build_ext')
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
    File "setup.py", line 41, in build_extensions
        numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in resource_filename
        return get_provider(package_or_requirement).get_resource_filename(
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 351, in get_provider
        __import__(moduleOrReq)
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/site-packages/numpy/__init__.py", line 158, in <module>
        from . import fft
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/site-packages/numpy/fft/__init__.py", line 15, in <module>
        import mkl_fft._numpy_fft as _nfft
    File "/data/jenkins/workspace/Pytesmo_installation/pytesmo_install/pytesmo_install/pytesmoenv/lib/python2.7/site-packages/mkl_fft/__init__.py", line 27, in <module>
        from ._pydfti import (fft, ifft, fft2, ifft2, fftn, ifftn, rfft, irfft,
    File "mkl_fft/_pydfti.pyx", line 32, in init mkl_fft._pydfti
    NameError: name 'ModuleNotFoundError' is not defined

However, if I install mkl_fft with pip (instead of conda), I get version 1.0.2 which *doesn't* cause this problem. I can also *uninstall* mkl_fft and run the tests without problems.

Yeah, I know that on Travis this problem doesn't seem to occur - I guess because mkl_fft isn't installed there (probably because the CPUs there don't identify as Intel?)

So there is a workaround but it looks like compiling and testing pytesmo doesn't work out of the box for Python 2.7 any more?

**Comment by cpaulik** [comment]
As you can see in your conda-list your numpy is not installed from conda-forge but from the default channel. The `-c conda-forge` in the install command should set it as the highest priority but the dependency resolution algorithm might thing that the defaults channel has to be taken.
See also https://conda.io/docs/user-guide/tasks/manage-channels.html

Conda can be confusing but you can always make yourself an `environment.yml` file with the fixed versions if you depend on repeatable installs. See [here](https://conda.io/docs/user-guide/tasks/manage-environments.html#sharing-an-environment) and [here](https://conda.io/docs/user-guide/tasks/manage-environments.html#building-identical-conda-environments)

**Comment by awst-baum** [comment]
You don't seem to mind that doing something very similar to the installation instructions in [the docs](https://pytesmo.readthedocs.io/en/latest/introduction.html#conda) leads to failing tests for some systems? What's your perspective there - pytesmo is aimed mainly at expert users who can sort this out for themselves?

In any case, what works for me now is doing this:

    conda create --yes -p pytesmo -c conda-forge python=2.7 pip
    source activate pytesmo
    conda config --env --add pinned_packages conda-forge::numpy
    conda install --yes -c conda-forge numpy scipy pandas netCDF4 cython pytest matplotlib pyproj
    pip install pygeogrids
    pip install pyresample
    pip install pytesmo

**Comment by awst-baum** [comment]
Ah, OK, good to know :) I expected the problem to be more long-term - but if you say they usually fix it within a few days that's reassuring.

I also like to test against the latest versions (in fact, that's why I created the whole build job on our buildserver at all: to be sure our stuff always works with the latest libs). Maybe I should actually test against python 3.6 ;)
